server:
  port: 8080

spring:
  application:
    name: rubrica

  datasource:
    url: jdbc:mysql://localhost:3306/rubrica_sannino
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # create, create-drop, update, validate, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      jakarta:
        persistence:
          validation:
            mode: none   # disabilita la validazione Jakarta
